Repository cryptimeleon/incentive-system, pull requests merged in 2022-11, with the labels that each got.

#176 Feature/basket db
  services/basket/build.gradle
  services/basket/src/main/java/org/cryptimeleon/incentive/services/basket/BasketController.java
  services/basket/src/main/java/org/cryptimeleon/incentive/services/basket/BasketService.java
  services/basket/src/main/java/org/cryptimeleon/incentive/services/basket/model/Basket.java
  services/basket/src/main/java/org/cryptimeleon/incentive/services/basket/model/BasketItem.java
  services/basket/src/main/java/org/cryptimeleon/incentive/services/basket/model/Item.java
  services/basket/src/main/java/org/cryptimeleon/incentive/services/basket/storage/BasketEntity.java
  services/basket/src/main/java/org/cryptimeleon/incentive/services/basket/storage/BasketRepository.java
  services/basket/src/main/java/org/cryptimeleon/incentive/services/basket/storage/ItemEntity.java
  services/basket/src/main/java/org/cryptimeleon/incentive/services/basket/storage/ItemInBasketEntity.java
  services/basket/src/main/java/org/cryptimeleon/incentive/services/basket/storage/ItemInBasketId.java
  services/basket/src/main/java/org/cryptimeleon/incentive/services/basket/storage/ItemRepository.java
  services/basket/src/main/resources/application.properties
  services/basket/src/test/java/org/cryptimeleon/incentive/services/basket/BasketTest.java
  services/basket/src/test/java/org/cryptimeleon/incentive/services/basket/ItemsTest.java
  services/basket/src/test/java/org/cryptimeleon/incentive/services/basket/PayBasketTest.java
  services/basket/src/test/java/org/cryptimeleon/incentive/services/basket/RedeemTest.java
  services/basket/src/test/java/org/cryptimeleon/incentive/services/basket/RewardItemsTest.java
Labels: enhancement

#177 Feature/store frontend
  services/basket/src/main/java/org/cryptimeleon/incentive/services/basket/BasketController.java
  services/basket/src/main/java/org/cryptimeleon/incentive/services/basket/BasketService.java
  services/basket/src/main/java/org/cryptimeleon/incentive/services/basket/model/Basket.java
  services/dsprotection/src/main/java/org/cryptimeleon/incentive/services/dsprotection/DsprotectionController.java
  web/src/components/IncHeader.vue
  web/src/components/dsprot/DsProtMain.vue
  web/src/components/dsprot/Transaction.vue
  web/src/components/store/Basket.vue
  web/src/components/store/BasketList.vue
  web/src/components/store/Item.vue
  web/src/components/store/ItemList.vue
  web/src/components/store/StoreMain.vue
  web/src/router/index.js
  web/vue.config.js
Labels: enhancement, frontend

#182 Hotfix/dsp logic
  services/incentive/src/main/java/org/cryptimeleon/incentive/services/incentive/DosService.java
  services/incentive/src/main/java/org/cryptimeleon/incentive/services/incentive/IncentiveService.java
  services/incentive/src/main/java/org/cryptimeleon/incentive/services/incentive/repository/CyclingScheduler.java
  services/incentive/src/main/java/org/cryptimeleon/incentive/services/incentive/repository/OfflineDSPRepository.java
  services/incentive/src/main/java/org/cryptimeleon/incentive/services/incentive/repository/ScheduledOfflineDSPRepository.java
  services/incentive/src/test/java/org/cryptimeleon/incentive/services/incentive/FakeScheduledOfflineDSPRepository.java
  services/incentive/src/test/java/org/cryptimeleon/incentive/services/incentive/IncentiveServiceTest.java
Labels: bug
